Change hash key so that multiple orderlines can be updated
sul-dlss/selved-wrapper-ruby pull request #21
Opened 2020-11-02 22:59 UTC by jgreben

Fixes https://github.com/sul-dlss/LibSysTasks/issues/686

This wrapper was using a hash with the order key as the has key. Because multiple order lines use the same order key, the resulting pipe-delim file was missing rows of data. This changes the hash key to be a concatenation of the orderline key + fund id.

The downside of this change is that we would not be able to use this selved wrapper independent of the data generated by the Expenditure report, but that is the only use case right now.

2020-11-02 23:01 UTC, jgreben commented on SelvedWrapper/return_all_input.rb
> +      key = line_array.slice(8..9).join('_')
Note this looks for particular pipe fields that are output by the `selorderlin` function of the expend report.

2020-11-03 23:01 UTC, dlrueda commented
I’d like @shelleydoljack to review this and merge if it seems good.  I totally agree that the key made up of the orderlin key + fundID is going to work.  But someone more versed in ruby should approve and merge this PR

2020-11-04 18:08 UTC, shelleydoljack requested changes
Looks good to me. I'd just like a comment that shows what the different pipe-delimited fields are for the expected selorderlin output for populate_hash.

2020-11-04 18:08 UTC, shelleydoljack commented on SelvedWrapper/return_all_input.rb
> +      key = line_array.slice(8..9).join('_')
I know it's in the fixture data, but it might be helpful to put an example of the expected selorderlin output that is parsed here as a comment, such as "order key|date|etc.".

2020-11-04 18:35 UTC, merged